theme = "hugo-theme-minos"
baseURL = "http://braultg.github.io/"
publishDir = "../braultg.github.io"
languageCode = "en-us"
title = "My New Hugo Site"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]